### PR TITLE
adds meetings page w/ proposed agenda for kickoff

### PR DESCRIPTION
**Pull request by neuromusic**
This PR adds a "meetings" page, including a proposed agenda for next week's kickoff meeting.

The agenda is open to discussion. There's a lot we want to fit in to a relatively short meeting. 

@LCObus: Does 10 minutes to present on UXR readout sound good?
@sofroniewn: How does 10 minutes for napari overview & roadmap sound?
@tlambert03: Is 25 minutes good for you?

### CODE REVIEW

**Comment by sofroniewn** [comment]
10 min overview is good for me

**Review by sofroniewn — APPROVED** [review]
Love using github to approve the agenda :-)

**Comment by neuromusic** [comment]
Got verbal approval from @LCObus

**Comment by tlambert03** [comment]
works for me!

**Review by tlambert03 — APPROVED** [review]

**Comment by neuromusic** [comment]
awesome, thank you all!

**Pull request merged**
